Description of abmn2n
Home > dcmatlab > data > abmn2n.m
abmn2n
PURPOSE
ABMN2N - Converts position arrays for A,B,M and N into data struct
SYNOPSIS
function N=abmn2n(AA,BB,MM,NN)
DESCRIPTION
 ABMN2N - Converts position arrays for A,B,M and N into data struct
 N = abmn2n(apos,bpos,mpos,npos);
 apos etc. is array (number of data, dimension)
CROSS-REFERENCE INFORMATION
This function calls:
getkonf GETKONF - Get configuration factor (calls getkonf2d/3d)
This function is called by:
loadradiccyl
reads2dfile READSND2D - Read 2d file by use of soundings
reads3dfile READSND3D - Read 3d file by use of soundings
readsnd2d READSND2D - Read 2d file by use of soundings
readsnd3d READSND3D - Read 3d file by use of soundings
SOURCE CODE
function N=abmn2n(AA,BB,MM,NN)
% ABMN2N - Converts position arrays for A,B,M and N into data struct
% N = abmn2n(apos,bpos,mpos,npos);
% apos etc. is array (number of data, dimension)
% [N.elec,SI,SJ]=unique([AA;BB;MM;NN],'rows');
N.elec=unique([AA;BB;MM;NN],'rows');
[TF,LOC]=ismember(AA,N.elec,'rows');
N.a=LOC;
[TF,LOC]=ismember(BB,N.elec,'rows');
N.b=LOC;
[TF,LOC]=ismember(MM,N.elec,'rows');
N.m=LOC;
[TF,LOC]=ismember(NN,N.elec,'rows');
N.n=LOC;
% [N.elec(N.a,1) N.elec(N.b,1) N.elec(N.m,1) N.elec(N.n,1)]
if size(N.elec,2)<2, N.elec(:,2)=0; end
N.k=getkonf(N);