Description of getkonf
Home > dcmatlab > data > getkonf.m
getkonf
PURPOSE
GETKONF - Get configuration factor (calls getkonf2d/3d)
SYNOPSIS
function konf=getkonf(varargin)
DESCRIPTION
 GETKONF - Get configuration factor (calls getkonf2d/3d)
 N.k = getkonf(N); % where N is data struct
CROSS-REFERENCE INFORMATION
This function calls:
getkonf2d GETKONF - Get Configuration factor from electrode positions
getkonf3d GETKONF - Get Configuration factor from electrode positions
This function is called by:
abmn2n ABMN2N - Converts position arrays for A,B,M and N into data struct
createsxhdata CREATESXHDATA - Create Surface-cross-borehole dataset
electrodeerr2d ELECTRODEERR2D - Error caused by electrode displacement (2d)
electrodeerr3d ELECTRODEERR3D - Error caused by electrode displacement (3d)
getkellipse GETKELLIPSE - Get geometric factor for half-ellipsoidal electrodes
read2drawfile READ2DRAWFILE - read 2d raw file
read3draw READ2DLB - Read 3D Raw Data File
read3drawfile READ3DRAWFILE - Read 3D Raw Data File
read4ch datfile='ddf3d4.org';
readampfile READAMPFILE - Read ABEM multi purpose file (*.amp)
readgemfile READGEMFILE - read sensinv3d file
readinv3dfile READINV3DFILE - Read data file in inv3d format
readlippmonfile filename='100210_1305.txt';
readmcffile mcffile='d:\Guenther.T\3d\jan\d16reip.mcf';
readres2dinvfile READRES2DINVFILE - Read 2D Loke&Barker File
readres2dinvfile1 READRES2DINVFILE - Read 2D Loke&Barker File
readres3dinvfile READRES3DINVFILE - Read 3D Loke&Barker File
reads2dfile READSND2D - Read 2d file by use of soundings
reads3dfile READSND3D - Read 3d file by use of soundings
readsnd2d READSND2D - Read 2d file by use of soundings
readsnd3d READSND3D - Read 3d file by use of soundings
readstgfile READSTGFILE - Read sting device file (*.stg)
SOURCE CODE
function konf=getkonf(varargin)
% GETKONF - Get configuration factor (calls getkonf2d/3d)
% N.k = getkonf(N); % where N is data struct
N=varargin{1};
if isfield(N,'elec'),
  if size(N.elec,2)>2,
    konf=getkonf3d(varargin{:});
  else
      fl=sqrt(sum(diff(N.elec([1 end],:)).^2));
      fm=sqrt(sum((N.elec(1,:)-mean(N.elec)).^2));
      if fl<fm, %apparently circle file
          konf=1;
      else
          konf=getkonf2d(varargin{:});
      end
  end
else
  error('No electrodes present!');
end