Description of readdatafile
Home > dcmatlab > data > readdatafile.m
readdatafile
PURPOSE
READDATAFILE - tries to read any data file
SYNOPSIS
function N=readdatafile(datfile)
DESCRIPTION
 READDATAFILE - tries to read any data file
CROSS-REFERENCE INFORMATION
This function calls:
read2dfile READ2DFILE - Read 2d data file (all file types)
read3dfile READ3DFILE - Read 3d data file (all file types)
This function is called by:
showasimage SHOWASIMAGE(Data[,field[,indices])
showdata SHOWDATA - Show data of any kind or dimension
SOURCE CODE
function N=readdatafile(datfile)
% READDATAFILE - tries to read any data file
if exist(datfile)~=2, error('File does not exist!'); end
[fpath,name,ext]=fileparts(datfile);
lext=lower(ext);
% check for res3dinv or unified data in 3d
is3d=false;
fid=fopen(datfile);
for i=1:4, zeile=fgetl(fid); end
if length(sscanf(destrip(zeile),'%f'))>2, is3d=true; end
fclose(fid);
if ismember(lext,{'.pro','s3d'})||is3d,
    N=read3dfile(datfile);
else
    N=read2dfile(datfile);
end