Description of showdata
Home > dcmatlab > data > showdata.m
showdata
PURPOSE
SHOWDATA - Show data of any kind or dimension
SYNOPSIS
function showdata(Data)
DESCRIPTION
 SHOWDATA - Show data of any kind or dimension
CROSS-REFERENCE INFORMATION
This function calls:
plotprofiles PLOTPROFILES - Plot profiles of a 3D data set
readdatafile READDATAFILE - tries to read any data file
showdata2d SHOWDATA2D show datum points
This function is called by:
geomerr GEOMERR - get geometrical error
SOURCE CODE
function showdata(Data)
% SHOWDATA - Show data of any kind or dimension
if isstr(Data),
    Data=readdatafile(Data);
end
if isfield(Data,'zweid'), % 3d profile data
    plotprofiles(Data);
else % no 3d profile data
    if ~isfield(Data,'elec')&&isfield(Data,'pos'), Data.elec=Data.pos; end
    if isfield(Data,'x'), % new tokens in
        %version 1: create elec out of it
        %version 2: do something real
        %patch2ddata(
        %return;
    end
    if isfield(Data,'elec'),
        %call old showdata
        showdata2d(Data);
        Data.x=Data.elec(:,1);
        if size(Data.elec,2)>1, Data.z=Data.elec(:,end); end
        %patch2ddata(Data)
    else
        display('could not display data!');
    end
end